### ISSUE TITLE
Assertion failed in p_mmap

### ISSUE THREAD

**Issue by ashleyblackmore** [libgit2/libgit2#2807]
Excuse me if this is the wrong place, but it looks to me that the underlying problem is with libgit2 (let me know if not, and I'll move this to pygit2's issue tracker). I'm cloning (using ssh transport), from pygit2.

```
python: /home/staging/Build/repobot/libgit2-0.21.2/src/unix/map.c:26: p_mmap: Assertion `out != ((void *)0) && len > 0' failed.
Aborted (core dumped)
```

My compilation process:

```
LIBGIT2_ARCHIVE = v0.21.2.tar.gz
LIBGIT2_URL = https://github.com/libgit2/libgit2/archive/$(LIBGIT2_ARCHIVE)
LIBGIT2_DIR = libgit2-0.21.2

setup_libgit2:
	wget -q --no-clobber $(LIBGIT2_URL)
	rm -rf $(LIBGIT2_DIR)
	tar zxf $(LIBGIT2_ARCHIVE)
	cd $(LIBGIT2_DIR) && cmake . -DCMAKE_INSTALL_PREFIX=$(VIRTUAL_ENV) -DTHREADSAFE=ON -DBUILD_CLAR=OFF
	make -C $(LIBGIT2_DIR) clean
	make -C $(LIBGIT2_DIR)
	make -C $(LIBGIT2_DIR) install
	sudo ldconfig
```

As you can see, I'm using libgit2 0.21.2, I will now try the RC and see how that goes.

**Comment by ashleyblackmore** [comment]
It is actually working now. Perhaps it was in fact a problem on the side of the git server. I suppose the upshot of this is that pygit2 should be perhaps handling this assertion with a clearer exception?

**Comment by carlosmn** [comment]
It looks like a bug which was fixed. If you can reproduce with 0.21.3 (or better yet, with the tip of `maint/v0.21`) then it's worth taking a look. Otherwise it should be fixed already.

**Comment by ashleyblackmore** [comment]
I assume this isn't pushed to the RC either, correct? I tested the RC and got the same issue.

**Comment by carlosmn** [comment]
That's been fixed in master for quite a while now (which is where the commit comes from). This cannot have the same issue. How you are you testing against master?

**Comment by ashleyblackmore** [comment]
Okay so with a new virtualenv (this time not using venvgit2), I run `make setup_pygit2` from the following Makefile:

```
default: verify

LIBGIT2_VERSION = 0.22.0-rc1
LIBGIT2_ARCHIVE = v$(LIBGIT2_VERSION).tar.gz
LIBGIT2_URL = https://github.com/libgit2/libgit2/archive/$(LIBGIT2_ARCHIVE)
LIBGIT2_DIR = libgit2-$(LIBGIT2_VERSION)

setup_libgit2:
	wget -q --no-clobber $(LIBGIT2_URL)
	rm -rf $(LIBGIT2_DIR)
	tar zxf $(LIBGIT2_ARCHIVE)
	cd $(LIBGIT2_DIR) && cmake . -DCMAKE_INSTALL_PREFIX=$(VIRTUAL_ENV) -DTHREADSAFE=ON -DBUILD_CLAR=OFF
	make -C $(LIBGIT2_DIR) clean
	make -C $(LIBGIT2_DIR)
	sudo make -C $(LIBGIT2_DIR) install
	sudo ldconfig

verify_pygit2_installed:
	export LD_LIBRARY_PATH=$(VIRTUAL_ENV)/lib
	python -c 'import pygit2'

setup_pygit2:
	export LDFLAGS="-Wl,-rpath='$(VIRTUAL_ENV)/lib',--enable-new-dtags $LDFLAGS"
	make setup_libgit2
	pip install -r requirements.txt --upgrade
	make verify_pygit2_installed

install_pygit2:
	@echo "This script requires root privileges"
	make setup_pygit2

verify:
	sudo ldconfig
	make verify_pygit2_installed
```

So as you can see from the above, I'm using 0.22.0-rc1.

requirements.txt:

```
pygit2==0.21.4
```

I still get the same issue when cloning directly after this setup process:

```
13:35 $ python repobot.py
python: /home/ablackmore/Build/repoman/libgit2-0.21.2/src/unix/map.c:26: p_mmap: Assertion `out != ((void *)0) && len > 0' failed.
Aborted (core dumped)
```

Now I see that it is still somehow using libgit-0.21.2! That folder doesn't exist! Am I going made?

Right now trying to find out how that call to map.c is ever being initiated, presumably pygit2 is doing this. Perhaps I need to use a matching version of pygit2? Gah, so confused right now

**Comment by carlosmn** [comment]
It's using a v0.21 libgit2 because that's the libgit2 which pygit2 0.21 works with. Have you tried installing from 'maint/v0.21' into your venv?

**Comment by ashleyblackmore** [comment]
Cheers Carlos, appreciate all your help. That worked.

Thanks for all your work on libgit2 btw, it is an incredible piece of work!

I guess I will close this, since the actual bug has been fixed.
