### ISSUE TITLE
merge: bogus newline appended in the EOF on file conflict

### ISSUE THREAD

**Issue by niamster** [libgit2/libgit2#3294]
If commit with a conflict on a file is merged as `ours` and originally there's no newline in the file, the newline is appended.
In the following snippet file `0` initially didn't have newline, while after the merge it appeared.
```
*~>git lol 0
*   9ba607b Merge 26b6a3e8203aefd5382aa4349f98d577e8f8e53f into refs/heads/master
|\
| * 26b6a3e commit file 0 v.1
* 41c5194 commit file 0 v.0
===================================================================
*~>git show 41c5194
commit 41c5194707433382f32278af6567853d01a6b94a
    commit file 0 v.0
diff --git a/0 b/0
new file mode 100644
index 0000000..23475bd
--- /dev/null
+++ b/0
@@ -0,0 +1 @@
+content of file 0 v.0
\ No newline at end of file
===================================================================
*~>git show 26b6a3e
commit 26b6a3e8203aefd5382aa4349f98d577e8f8e53f
    commit file 0 v.1
diff --git a/0 b/0
new file mode 100644
index 0000000..c9da6f9
--- /dev/null
+++ b/0
@@ -0,0 +1 @@
+content of file 0 v.1
\ No newline at end of file
===================================================================
*~>git show 9ba607b
commit 9ba607b6825a02437c27a7b2d61a4ebf44ae521e
Merge: e147d4d 26b6a3e
    Merge 26b6a3e8203aefd5382aa4349f98d577e8f8e53f into refs/heads/master
diff --cc 0
index 23475bd,c9da6f9..92953f4
--- a/0
+++ b/0
@@@ -1,1 -1,1 +1,1 @@@
- content of file 0 v.0
 -content of file 0 v.1
++content of file 0 v.0
```

**Comment by ethomson** [comment]
So does `git-merge-recursive` when given the `ours` flag.

````
% hexdump -C foo
00000000  62 61 72                                          |bar|
00000003

% git merge -srecursive -Xours foo
Auto-merging foo
Merge made by the 'recursive' strategy.
 foo | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

% hexdump -C foo
00000000  62 61 72 0d 0a                                    |bar..|
00000005
````

If you believe that this is a bug, this should be fixed in git.git and we will update to match.

**Comment by niamster** [comment]
@ethomson  thanks for the reply. In fact it does not (with GIT 2.4.3).
I have tried both `recursive` and `ours` and in both cases the file didn't have newline:
```
*~>git show master
commit ee5272689d856e1f6e32c3065426fb308b241505
diff --git a/0 b/0
index c227083..56a6051 100644
--- a/0
+++ b/0
@@ -1 +1 @@
-0
\ No newline at end of file
+1
\ No newline at end of file
==========================================
*~>git show release
commit ee5272689d856e1f6e32c3065426fb308b241505
    v1
diff --git a/0 b/0
index c227083..56a6051 100644
--- a/0
+++ b/0
@@ -1 +1 @@
-0
\ No newline at end of file
+1
\ No newline at end of file
==========================================
*~>git show master~1
commit 697bd3506b88a25dcfdd17f94c692a0c4244736c
    v0
diff --git a/0 b/0
new file mode 100644
index 0000000..c227083
--- /dev/null
+++ b/0
@@ -0,0 +1 @@
+0
\ No newline at end of file 

Also please note that `-srecursive -sours` is just a hint to GIT which strategy to try. The are not combined for a single commit. In your case it used `recursive` and I _bet_ that in the other branch `foo` had newline.

**Comment by ethomson** [comment]
> Also please note that `-srecursive -sours` is just a hint to GIT which strategy to try.

`-Xours`, not `-sours`.  `-X` provides strategy options (in this case `ours`) to the `-s` resolution strategy (in this case `recursive`.)  `-srecursive -Xours` and `-sours` are completely different animals.

I'll take a look to see if something has changed here between 1.9.5 and 2.4.

**Comment by niamster** [comment]
I'm not pro in GIT so unfortunately I don't see any difference between `-srecursive -Xours` and `-sours` in this particular case.
Anyways, in case of `-srecursive -Xours` I still don't see the newline.

**Comment by ethomson** [comment]
`-srecursive -Xours` will merge the two trees, using the "ours" side only in the event of a conflict.  `-sours` will take the entirety of the "ours" tree.  One will take a (non-conflicting) change from the theirs side, the other will blow away all changes in the theirs side.  (The latter is not a merge at all, it only records a merge in the graph.)

**Comment by niamster** [comment]
Thanks for the clarification. Here I'm using `ours` to filter out commits that I want to block during the merge.

**Comment by ethomson** [comment]
Thanks for the report, I ported the latest xdiff from core git which fixes this issue.

**Comment by niamster** [comment]
Thanks @ethomson. I confirm it fixes the issue.

**Comment by ethomson** [comment]
:+1: Thanks for the confirmation!
