### ISSUE TITLE
libgit2 assumes everything not under refs/tags are commits

### ISSUE THREAD

**Issue by asandroq** [libgit2/libgit2#3595]
In my application that uses `libgit2` I create tags to blobs (which is unusual because tags normally point to commit objects) and create symbolic references to those tags under `refs/snapshots`. The `git` program has no problems fetching those references:

```
10:37 $ git fetch origin refs/snapshots/*:refs/snapshots/*
remote: Counting objects: 2, done
remote: Finding sources: 100% (2/2)
remote: Total 2 (delta 0), reused 2 (delta 0)
Unpacking objects: 100% (2/2), done.
From ssh://gerrit.qnective.com:29418/qtalk_proj
 * [new ref]         refs/snapshots/bc1b0ddb-37b8-44b3-9589-9e31bf17c95b -> refs/snapshots/bc1b0ddb-37b8-44b3-9589-9e31bf17c95b
```

But `libgit2` fails with "Object is not a committish". In `smart_protocol.c`, function `fetch_setup_walk` we can see a call to `git_revwalk_push`, which will assume the reference must be a commit, which is not always the case.

**Comment by carlosmn** [comment]
Which libgit2 are you using? This issue should have been fixed a while ago.

**Comment by asandroq** [comment]
Sorry, I forgot to add more info:
* libgit2 version 0.23.4
* GCC 5.3.0
* Ubuntu Linux 14.04

**Comment by carlosmn** [comment]
Can you try with `master`? There's some stuff we don't backport when it depends on code changes that have happened in the main branch.

**Comment by ethomson** [comment]
Now that we've shipped [0.24](https://github.com/libgit2/libgit2/releases/tag/v0.24.0), these changes should have landed in a released version.  Closing this issue - @asandroq please reopen if you're still seeing this problem in 0.24.

Thanks!

**Comment by asandroq** [comment]
I have upgraded my dependency to libgit2 0.24 and I still see the issue. This is the patch I am using for now:

```diff
diff --git a/src/transports/smart_protocol.c b/src/transports/smart_protocol.c
index 1d46d4b..324f6d0 100644
--- a/src/transports/smart_protocol.c
+++ b/src/transports/smart_protocol.c
@@ -274,6 +274,9 @@ static int fetch_setup_walk(git_revwalk **out, git_repository *repo)
 	git_revwalk_sorting(walk, GIT_SORT_TIME);
 
 	for (i = 0; i < refs.count; ++i) {
+		const git_oid *oid;
+		git_object *obj, *oobj;
+
 		/* No tags */
 		if (!git__prefixcmp(refs.strings[i], GIT_REFS_TAGS_DIR))
 			continue;
@@ -284,7 +287,22 @@ static int fetch_setup_walk(git_revwalk **out, git_repository *repo)
 		if (git_reference_type(ref) == GIT_REF_SYMBOLIC)
 			continue;
 
-		if ((error = git_revwalk_push(walk, git_reference_target(ref))) < 0)
+                /* only walk over commits */
+                oid = git_reference_target(ref);
+                if ((error = git_object_lookup(&oobj, repo, oid, GIT_OBJ_ANY)) < 0)
+                        goto on_error;
+
+                error = git_object_peel(&obj, oobj, GIT_OBJ_COMMIT);
+                git_object_free(oobj);
+                if (error == GIT_ENOTFOUND || error == GIT_EPEEL) {
+                        git_reference_free(ref);
+                        continue;
+                } else if (error != 0)
+                        goto on_error;
+
+                git_object_free(obj);
+
+		if ((error = git_revwalk_push(walk, oid)) < 0)
 			goto on_error;
 
 		git_reference_free(ref);
```

**Comment by asandroq** [comment]
@ethomson It seems I cannot reopen this issue by myself.

**Comment by asandroq** [comment]
Still present in version 0.25.1.

**Comment by pks-t** [comment]
I think here's something else at play, your change simply papers over that deficiency. As can be seen in `fetch_setup_walk`, we intend not to add tags in the first place:

```
		if (!git__prefixcmp(refs.strings[i], GIT_REFS_TAGS_DIR))
			goto on_continue;
```

For everything else, we sohuld be able to assume that it is a commit-ish. Which references do you have in particular which are not pointing to a commit-ish?

**Comment by asandroq** [comment]
Hi,

As I mentioned in my first message, I have tags that point to blobs instead of to commits.

**Comment by biodranik** [comment]
This issue is still there in the 0.28.2 version.
