### ISSUE TITLE
Fatal error running clar tests on MacOS, CentOS 7

### ISSUE THREAD

**Issue by jonathanturcotte** [libgit2/libgit2#4959]
### Version of libgit2 (release number or SHA1)
libgit2-0.27.7

### Operating system(s) tested
macOS 10.14.2
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

CentOS 7.2.1511
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

### Reproduction steps
```
$ mkdir build && cd build
$ cmake ..
$ cmake --build .
$ ./libgit2_clar
```
Many tests fail, and then clar encounters a fatal error. Tested on both my macbook and a CentOS 7 server, with the same results on both. Found #4920, which seems to be the same issue as I am having, however reinstalling xcode-tools as suggested there didn't work for me on my mac. Here's the output of running the clar tests, as far as I can tell the output is identical between mac and centos.

```
Loaded 349 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.....................................................................................................................S.........................FF.FFFF....F....F.........................................................................................................................................................................................................................................................................................................................................................................................................S...S.SS.S.............................................................................................................................................FF.FF.....................FFFFFFF.F.F..................FFF................FFF.....F.....F.............F.....FFF..................FFFF.FF.............FFFFFFF..F.F...FFFF...FF.FF.S.......................................S..........FF............S.........................................................................................................................................................................S...........FFFFFFFFFFFFatal error: a cleanup method raised an exception.  1) Failure:
merge::driver::not_configured_driver_falls_back [/Users/jonathan/libgit2-0.27.7/tests/merge/driver.c:144]
  Function call failed: (git_merge(repo, (const git_annotated_commit **)&their_head, 1, ((void *)0), ((void *)0)))
  error -13 - 4 uncommitted changes would be overwritten by merge
  2) Failure:
merge::driver::not_configured_driver_falls_back [/Users/jonathan/libgit2-0.27.7/tests/merge/driver.c:114]
  Function call failed: (git_merge_driver_unregister("custom"))
  error -3 - cannot find merge driver 'custom' to unregister
```

**Comment by ethomson** [comment]
I have no possible idea.  I've never seen this before and we run our build and test suite on macOS for every commit.  (I just ran it in CentOS without any difficulty.)

Anything strange about your environment?  Trying to use a ramdisk or anything for temp?  Network shares for home directories?

**Comment by jonathanturcotte** [comment]
I spun up a vanilla RHEL 7.4 image, yum installed gcc, cmake, openssl, etc, and then the tests are passing, so it's definitely something about the build environment.

I'm pretty confident we're not doing either of those things on the centos box, and I'm sure neither of those things are being done on my macbook. 

Interestingly, when my coworker ran the build on his mac (10.14.3), he got different failures than I did and it didn't fatally error.

**Comment by tiennou** [comment]
I may have seen it once, which I accidentally fixed by panicking. I don't remember what exact steps I took though (that's what bad about panic), but it was very weird indeed.

**Comment by jonathanturcotte** [comment]
I decided to give the latest 0.27.8 version a try, and weirdly enough the Centos 7 server now passes just fine. I don't think it's the update to the latest version, instead I think something changed in my environment, but I'm frankly not sure what changed. 

The latest version was still failing on my mac with the fatal error, but after removing all my homebrew packages it now completes, albeit with plenty of failures. I have a hunch that the homebrew binutils package might have been involved somehow.

**Comment by ethomson** [comment]
> The latest version was still failing on my mac with the fatal error, but after removing all my homebrew packages it now completes, albeit with plenty of failures.

If you're still getting test failures, I'm still concerned.

**Comment by pks-t** [comment]
On Wed, Jan 30, 2019 at 08:58:19PM +0000, Jonathan Turcotte wrote:
> I decided to give the latest 0.27.8 version a try, and weirdly
> enough the Centos 7 server now passes just fine. I don't think
> it's the update to the latest version, instead I think
> something changed in my environment, but I'm frankly not sure
> what changed.
> 
> The latest version was still failing on my mac with the fatal
> error, but after removing all my homebrew packages it now
> completes, albeit with plenty of failures. I have a hunch that
> the homebrew binutils package might have been involved somehow.

Did you accidentally mess with your clone of libgit2? For me,
I've sometimes hit an issue where there was a ".git" folder
inside of our tests that is silently being ignored by Git so you
don't spot it when doing `git status`. So you might want to try
in a fresh clone, just to make sure this isn't the case.

If that doesn't help, could you please post the output from CMake
when configuring a new build directory? Maybe there's something
to see.

**Comment by jonathanturcotte** [comment]
Re-downloaded the latest release to make sure, and I don't seem to be having the fatal error issue anymore. Honestly not sure if there was something wrong with my original folder or if re-installing some of the homebrew packages and then rebooting helped. Or it could have been the Sorry all the inconsistencies, I'm really not sure what is changing in my build environment seemingly day to day.

Here is the output of my cmake configure:

```
jonathan@jonathan:~/Downloads/libgit2-0.27.8/build $ cmake ..
-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Success
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Success
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WSHIFT-COUNT-OVERFLOW_SUPPORTED
-- Performing Test IS_WSHIFT-COUNT-OVERFLOW_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Performing Test IS_WFORMAT_SUPPORTED
-- Performing Test IS_WFORMAT_SUPPORTED - Success
-- Performing Test IS_WFORMAT-SECURITY_SUPPORTED
-- Performing Test IS_WFORMAT-SECURITY_SUPPORTED - Success
-- Performing Test IS_WINT-CONVERSION_SUPPORTED
-- Performing Test IS_WINT-CONVERSION_SUPPORTED - Success
-- Performing Test IS_WNO-DEPRECATED-DECLARATIONS_SUPPORTED
-- Performing Test IS_WNO-DEPRECATED-DECLARATIONS_SUPPORTED - Success
-- Looking for regcomp_l
-- Looking for regcomp_l - found
-- Looking for futimens
-- Looking for futimens - found
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - True
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - False
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Found Security /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework
-- Looking for SSLCreateContext in /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework
-- Looking for SSLCreateContext in /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework - found
-- Found CoreFoundation /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework
-- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Found Iconv: -L/usr/lib -liconv
-- Found PythonInterp: /usr/bin/python (found version "2.7.10")
-- Enabled features:
 * threadsafe, threadsafe support
 * HTTPS, using SecureTransport
 * SHA, using CollisionDetection
 * http-parser, http-parser support (bundled)
 * zlib, using system zlib
 * iconv, iconv encoding conversion support
-- Disabled features:
 * debugpool, debug pool allocator
 * tracing, tracing support
 * cURL, cURL for HTTP proxy support
 * SSH, SSH transport support
 * SPNEGO, SPNEGO authentication support
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jonathan/Downloads/libgit2-0.27.8/build
```

And here are the failing tests:

```
jonathan@jonathan:~/Downloads/libgit2-0.27.8/build $ ./libgit2_clar
Loaded 350 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.....................................................................................................................S.....................................................................................................................................................................................................................................................................................................................................................................................................................................................S...S.SS.S.............................................................................................................................................................................FFFF........................FF...........................................................................................F..FFF................FF....S.......................................S........................S.........................................................................................................................................................F...F...........S.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SSSSSS.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.....................F................................................................................................................................................................................................................................FF.F..FF.F..................F.......F.............................................................................SSSSSS..................................................................................................
  1) Failure:
diff::diffiter::iterate_files_and_hunks [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/diffiter.c:115]
  13 != file_count
  13 != 12
  2) Failure:
diff::diffiter::max_size_threshold [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/diffiter.c:154]
  13 != file_count
  13 != 12
  3) Failure:
diff::diffiter::iterate_all [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/diffiter.c:245]
  13 != exp.files
  13 != 12
  4) Failure:
diff::diffiter::iterate_randomly_while_saving_state [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/diffiter.c:329]
  13 != exp.files
  13 != 12
  5) Failure:
diff::notify::notify_catchall_with_empty_pathspecs [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/notify.c:64]
  expected_diffed_files_count != exp.files
  13 != 12
  6) Failure:
diff::notify::notify_catchall [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/notify.c:64]
  expected_diffed_files_count != exp.files
  13 != 12
  7) Failure:
diff::workdir::to_index [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:46]
  13 != exp.files
  13 != 12
  8) Failure:
diff::workdir::to_tree [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:216]
  14 != exp.files
  14 != 13
  9) Failure:
diff::workdir::to_index_with_pathspec [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:369]
  13 != exp.files
  13 != 12
  10) Failure:
diff::workdir::to_index_with_pathlist_disabling_fnmatch [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:478]
  13 != exp.files
  13 != 12
  11) Failure:
diff::workdir::with_stale_index [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:1723]
  17 != exp.files
  17 != 16
  12) Failure:
diff::workdir::can_update_index [/Users/jonathan/Downloads/libgit2-0.27.8/tests/diff/workdir.c:1788]
  13 != exp.files
  13 != 12
  13) Failure:
iterator::workdir::1 [/Users/jonathan/Downloads/libgit2-0.27.8/tests/iterator/workdir.c:71]
  expected_count != count
  13 != 12
  14) Failure:
iterator::workdir::1_ranged_4 [/Users/jonathan/Downloads/libgit2-0.27.8/tests/iterator/workdir.c:71]
  expected_count != count
  4 != 3
  15) Failure:
repo::pathspec::workdir4 [/Users/jonathan/Downloads/libgit2-0.27.8/tests/repo/pathspec.c:169]
  13 != git_pathspec_match_list_entrycount(m)
  13 != 12
  16) Failure:
status::worktree::whole_repository [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:41]
  counts.expected_entry_count != counts.entry_count
  16 != 15
  17) Failure:
status::worktree::show_index_and_workdir [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:69]
  counts.expected_entry_count != counts.entry_count
  16 != 15
  18) Failure:
status::worktree::show_workdir_only [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:69]
  counts.expected_entry_count != counts.entry_count
  13 != 12
  19) Failure:
status::worktree::swap_subdir_and_file [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:182]
  counts.expected_entry_count != counts.entry_count
  22 != 21
  20) Failure:
status::worktree::swap_subdir_with_recurse_and_pathspec [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:216]
  counts.expected_entry_count != counts.entry_count
  23 != 22
  21) Failure:
status::worktree::single_file [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:283]
  Function call failed: (git_status_file(&status_flags, repo, entry_paths0[i]))
  error -3 - attempt to get status of nonexistent file '这'
  22) Failure:
status::worktree::conflict_has_no_oid [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:719]
  16 != git_status_list_entrycount(statuslist)
  16 != 15
  23) Failure:
status::worktree::update_stat_cache_0 [/Users/jonathan/Downloads/libgit2-0.27.8/tests/status/worktree.c:989]
  entry_count0 != max_i
  16 != 15
```
 It looks like all the counts are just off by one?

**Comment by ethomson** [comment]
Aha.  So, it looks like you've downloaded the release zip from the [releases page](https://github.com/libgit2/libgit2/releases)?

I went through those, and it looks like there's a problem with those automatically generated zip archives.  (The build and test should pass when you check out that tag from a git repository, and I tested the automatically generated tarball as well.)  I'm guessing that one of the funny filenames isn't getting added to the zip file for some reason.

Regrettably, since these are automatically generated, we can't remove them.  But I think that if you either clone the repository or download the tar.gz, then things should work better for you.

**Comment by jonathanturcotte** [comment]
Ahhh yeah, downloading the tar version works. Note entirely sure what solved the original fatal error I was getting, but at least now I have passing tests! Thank you for all your help!

**Comment by ethomson** [comment]
> Not entirely sure what solved the original fatal error I was getting, but at least now I have passing tests!

Those are also related - it turns out that the test infrastructure will report a "fatal error" if the cleanup functions fail.  (A failure in a test function is just a failure of the test, a failure in the test function's cleanup routine is a fatal error.)

The cleanup bits failed (I think) because the whole test resources directory isn't Quite Right, and so it's expecting to be able to remove a file but that doesn't actually exist.  I _hope_ that the failing test isn't causing the whole test to fatal error, but I suppose that's also a possibility.
