### ISSUE TITLE
Negate patterns in .gitignore

### ISSUE THREAD

**Issue by buddyspike** [libgit2/libgit2#4963]
I have a repository with following structure

```
/
  .gitignore
  subdir/
    .gitignore
```

In the root `.gitignore` file there's a negate rule `!*[Cc]ache/`.
`.gitignore` file in `subdir` has the opposite rule `.cache/`

With that setup, if I create a file `subdir/.cache/foo`, `git status` does not report it. However, it is reported when invoking `git_status_list_new` with `GIT_DIFF_INCLUDE_UNTRACKED` option. 

Is that behaviour normal?

BTW: This happens in `v27.x`, `v26` is fine.

**Comment by pks-t** [comment]
Which version of libgit2 are you using? The reason why I'm asking
is because we fixed an issue that sounds exactly like yours in
#4670. This PR is not yet part of any release, but it will be
included in v0.28.0 and the upcoming v0.27.8.

**Comment by buddyspike** [comment]
I'm on `0.27.7`. I will wait until `0.27.8` is out. 
Thanks for the awesome work! 😸

**Comment by ethomson** [comment]
Hey @buddyspike, I just dropped [v0.27.8](https://github.com/libgit2/libgit2/releases/tag/v0.27.8).  Can you see if this fixes your issue?

**Comment by buddyspike** [comment]
Unfortunately, my test is still failing.
Interestingly, the rule only breaks when I introduced `[Cc]` or `*` in the parent `.gitignore`. 
If it has just `!.cache/`, it works (even in `0.27.7`).

**Comment by buddyspike** [comment]
Following the changes in the commit, I wrote this test:

```c

void test_status_ignore__override_negate_rule(void)
{
	static const char *test_files[] = {
		"empty_standard_repo/.cache/a.test",
		"empty_standard_repo/subdir/.cache/b.test",
		NULL
	};

	make_test_data("empty_standard_repo", test_files);
	cl_git_mkfile(
		"empty_standard_repo/.gitignore",
		"!*.[Cc]ache/\n");

	cl_git_mkfile(
		"empty_standard_repo/subdir/.gitignore",
		".cache/\n");

	assert_is_ignored("subdir/.cache/b.test");
	refute_is_ignored(".cache/a.test");
}
```

It passes. I wonder if the problem is somewhere else 😉.

**Comment by pks-t** [comment]
On Tue, Jan 29, 2019 at 09:49:47AM +0000, Buddhike de Silva wrote:
> Following the changes in the commit, I wrote this test:
> 
> ```c
> 
> void test_status_ignore__override_negate_rule(void)
> {
> 	static const char *test_files[] = {
> 		"empty_standard_repo/.cache/a.test",
> 		"empty_standard_repo/subdir/.cache/b.test",
> 		NULL
> 	};
> 
> 	make_test_data("empty_standard_repo", test_files);
> 	cl_git_mkfile(
> 		"empty_standard_repo/.gitignore",
> 		"!*.[Cc]ache/\n");
> 
> 	cl_git_mkfile(
> 		"empty_standard_repo/subdir/.gitignore",
> 		".cache/\n");
> 
> 	assert_is_ignored("subdir/.cache/b.test");
> 	refute_is_ignored(".cache/a.test");
> }
> ```
> 
> It passes. I wonder if the problem is somewhere else 😉.

Hum. Do you also have a minimal reproducer that exhibits the
problem with `git_status_list_new`?

**Comment by buddyspike** [comment]
Sorry @pks-t, don't have one right away. I will try to update the test above.

As bit of background for the time being, this problem occurs in this test:
https://github.com/mbtproject/mbt/blob/master/lib/repo_test.go#L222

which eventually calls `StatusList` in `git2go` with options like this:
https://github.com/mbtproject/mbt/blob/master/lib/repo.go#L337

**Comment by buddyspike** [comment]
Sorry folks, this has been a problem on my end as I was using `GIT_STATUS_OPT_INCLUDE_UNTRACKED` 😄

**Comment by buddyspike** [comment]
Hmm.. had another closer look, I think something is wrong. Finally managed to reproduce it consistently with steps outlined below. 

Create a new directory and initialise it with following.
```
#!/bin/sh

set -ex

git init

cat << EOF > .gitignore
!*cache/

EOF

mkdir subdir
cat << EOF > subdir/.gitignore
.cache/

EOF

mkdir subdir/.cache

touch subdir/.cache/a

git add -A
git commit -m "first"
```

Now run `git status` and you will see a clean working tree.

However, if you run `status.c` from examples directory in libgit2, you will see `subdir/.cache` as modified.

@ethomson & @pks-t that doesn't look right? I'm wrapping my head around libgit2, let me know if you guys beat me to it.

**Comment by LinArcX** [comment]
I have same problem. i try to get status of a clean project. But status.c shows me those files that ignored via __.gitignore__ file.

**Comment by buddyspike** [comment]
@LinArcX Could you please take this patch and see if your scenario works? If it was broken due to a negative wild card, this should do the trick.
